<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;
use Fisharebest\Webtrees\Http\RequestHandlers\ControlPanel;

?>

<?= view('components/breadcrumbs', ['links' => [route(ControlPanel::class) => I18N::translate('Control panel'), $title]]) ?>

<h1><?= $title ?></h1>

<div class="jc-fancy-research-links mb-5">
    <p><?= I18N::translate('Check the plugins you want to use in the sidebar.') ?></p>
    <p><?= I18N::translate('Hit the radio button in front of an research area title to set that research area as default. The chosen research area will open unfolded in the sidebar.') ?></p>
    <hr class="border-top border-secondary w-100">

    <form method="post">
        <?= csrf_field() ?>
        <input type="hidden" name="save" id="save" value="1">
        <!-- SELECT ALL -->
        <div class="row form-group justify-content-between">
            <div class="col">
                <?= view('components/checkbox', ['label' => 'select-all', 'name' => 'select-all']) ?>
            </div>
            <!-- OPEN LINKS IN NEW TAB -->
            <div class="col text-right">
                <?= view('components/checkbox', ['label' => 'Open links in a new tab', 'name' => 'target-blank', 'checked' => (bool) $target_blank]) ?>
                <p class="small text-muted"><i class="fa fa-exclamation-triangle"></i> <?= I18N::translate('Enabling this will change the default behavior of the browser.') ?></p>
            </div>
        </div>
        <!-- RESEARCH LINKS -->
        <?php foreach ($plugins as $area => $plugins_by_area): ?>
            <div class="form-group col-sm-12">
                <div class="radio">
                    <label class="radio">
                        <input
                            type="radio"
                            name="expanded-area"
                            value="<?= $area ?>"
                            <?php if ($expanded_area === $area): ?>
                                checked="checked";
                            <?php endif; ?>
                            >
                        <span class="h4"><?= $area ?></span>
                    </label>
                </div>
                <div class="row">
                <?php foreach ($plugins_by_area as $plugin): ?>
                    <?php $checked = (bool) $enabled_plugins->has($plugin->pluginName()) ?>
                    <div class="checkbox col-sm-4" dir="ltr">
                        <label class="checkbox-inline">
                            <?= view('components/checkbox-inline', ['label' => $plugin->pluginLabel(), 'name' => 'enabled-plugins[' . $plugin->pluginName() . ']', 'checked' => $checked]) ?>
                        </label>
                    </div>
                <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
        <button type="submit" class="btn btn-primary">
            <?= view('icons/save') ?>
            <?= I18N::translate('save') ?>
        </button>
    </form>
</div>

<?php View::push('javascript') ?>
<script>
    $('#select-all-1').change(function(e) {
        if (e.currentTarget.checked) {
            $('.form-group .row').find('input[type="checkbox"]').prop('checked', true);
        } else {
            $('.form-group .row').find('input[type="checkbox"]').prop('checked', false);
        }
    });
    $('#tree').on('change', function() {
        $('#save').val('0');
        $('form').submit();
        return false;
    });
</script>
<?php View::endpush() ?>
