<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

?>

<?= I18N::translate('Research links') ?>

<?php if ($is_admin): ?>
<a class="jc-config-link me-3" href="<?= e($module->getConfigLink()) ?>" title="<?= I18N::translate('Preferences') ?>">
    <?= view('icons/preferences') ?>
</a>

<?php View::push('javascript') ?>
<script>
    $('.jc-config-link')
        .parent('.accordion-button').after($('.jc-config-link'))
        .parent('.accordion-header').addClass('d-flex justify-content-between align-items-center')
</script>
<?php View::endpush() ?>
<?php endif ?>
