<?php

use Ramsey\Uuid\Uuid;
use Fisharebest\Webtrees\View;

?>

<div id="sb-jc-fancy-research-links">
    <!-- FANCY RESEARCH LINKS -->
    <?php foreach ($plugins as $area => $plugins_by_area): ?>
        <?php
            if ($expanded_area === $area) {
                $expanded = "true";
                $show = " show";
            } else {
                $expanded = "false";
                $show = "";
            }
            $id = 'collapse-' . Uuid::uuid4()->toString();

            $count = 0;
            foreach ($plugins_by_area as $plugin) {
                if ($enabled_plugins->contains($plugin->pluginName())) {
                    $count = $count + 1;
                }
            }
        ?>
        <div class="fancy-research-link-area mb-3">
            <?php if ($count > 0) : ?>
                <div>
                    <a href="#<?= e($id) ?>" role="button" data-toggle="collapse" aria-controls="<?= e($id) ?>" aria-expanded="<?= $expanded ?>">
                        <?= view('icons/expand') ?>
                        <?= view('icons/collapse') ?>
                        <span class="text-uppercase font-weight-bold"><?= $area ?></span>
                    </a>
                    <span class="badge badge-dark"><?= $count ?></span>
                </div>
                <ul class="collapse<?= $show ?>" id="<?= e($id) ?>">
                <?php foreach ($plugins_by_area as $plugin): ?>
                    <?php if ($enabled_plugins->contains($plugin->pluginName())) : ?>
                        <li class="pb-1"><a href="<?= e($plugin->researchLink($attributes)) ?>" target=<?= $target_blank ? "_blank" : "" ?>><?= $plugin->pluginLabel() ?></a></li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>
</div>

<?php if ($expand_sidebar) : ?>
<?php View::push('javascript') ?>
<script>
    $("#sidebar-content-family_nav").removeClass("show");
    $("#sidebar-content-_jc-fancy-research-links_").addClass("show");
</script>
<?php View::endpush() ?>
<?php endif; ?>
